name = "bdix-iptv-xtream"
main = "worker.js"
compatibility_date = "2026-09-26"

[vars]
PLAYLIST_URL = "https://raw.githubusercontent.com/saeidrahmanbd/BDIX-IPTV/main/IPTV%20Playlist.m3u"
TIMEZONE = "Asia/Dhaka"

[secrets]
required = ["XTREAM_USERNAME", "XTREAM_PASSWORD"]